config/routes.rb
Rainforest::Application.routes.draw do
  
  resources :products do
    resources :reviews, :except => [:index]
  end
  resources :users #, :only => [:new, :create, :update, :show, :update]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :categories, :except => :show

  root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/cats.rb
class Cats < ActiveRecord::Base
	belongs_to :product
	belongs_to :review
end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
  
  belongs_to :category

  has_many :reviews
  has_many :users, :through => :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :product

	# has_many :cats
	# has_many :products, :through => :cats

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :email, :on => :create
  validates_presence_of :password, :on => :create
  validates_presence_of :name

  has_many :reviews
  has_many :products, :through => :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user

	def ensure_logged_in
		unless current_user
			flash[:alert] = "Please log in"
			redirect_to new_session_path
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  # before_filter :load_product

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create

    @category = Category.new(category_params)

    if @category.save
      redirect_to root_path, notice: 'category created successfully'
    else
      render :action => :show
    end
  end

  def destroy
    @category = category.find(params[:id])
    @category.destroy
  end

  private

  def load_product
    @product = Product.find(params[:product_id])
    @category = @product.category
  end

  def category_params
    params.require(:category).permit(:description)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_filter :ensure_logged_in, :only => [:show]

  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def show
    #show the bloody product
    @product = Product.find(params[:id])
    #offer users the possibility to whine
    if current_user
      @review = @product.reviews.build
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  def create
    params.permit!
    @product = Product.new(params[:product])
    

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product,
        notice: 'Product was successfully created.' }
        format.json { render json: @product,
        status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors,
        status: :unprocessable_entity }
      end
    end
  end

  def update
    params.permit!
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product,
        notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors,
        status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]
  before_filter :load_product

  def show
    @review = Review.find(params[:id])
  end

  def create
    #@review = @product.reviews.build(params[:review])
    # Check out this article on [.build](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel)
    # You could use a longer alternate syntax if it makes more sense to you
    # 
    @review = Review.new(
      :comment    => params[:review][:comment], 
      :product_id => @product.id, 
      :user_id    => current_user.id
    )

    if @review.save
      redirect_to products_path, notice: 'Review created successfully'
    else
      render :action => :show
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to products_url, :notice => "Logged in!"
		else
			flash.now[:alert] = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to products_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  	params.permit!
    @user = User.new(params[:user])
    if @user.save
      redirect_to products_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    params.permit!
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      redirect_to products_url, :notice => "Profile was successfully updated"
    else
      render "show"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  
  <div class="field">
    <p>
      <%= f.label :description %><br/>
      <%= f.text_field :description %>
    </p>
  </div>
  <div class="actions"><%= f.submit :class => "button" %></div>
<% end %>

app/views/categories/_form_new.html.erb
<%= form_for [@category, @product] do |f| %>

<%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label "name" %><br>
    <%= f.text_field "name" %>
  </p>
  <p>
    <%= f.label "description" %><br>
    <%= f.text_field "description" %>
  </p>
  <p>
    <%= f.label "price_in_cents" %><br>
    <%= f.text_field "price_in_cents" %>
  </p>
  <!-- sending to a controller other than product -->
   <p>
     <%= f.label "price_in_cents" %><br>
    <%= f.text_field "price_in_cents" %>
  </p>
  <p>
    <%= submit_tag "Save", id: "submit", class: "button" %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit a category</h1>

<%= render 'form' %>

<%= link_to 'Back', product_category_path %>

app/views/categories/index.html.erb
<h1>Your Categories</h1>
<ul>
<% @categories.each do |cat| %>
	<li>
		Category <%= cat.id %>: <%= cat.description %>
	</li>
<% end %>
</ul>
<%= link_to 'New Category', new_category_path %></br>
<%= link_to 'Back', products_path %>

app/views/categories/new.html.erb
<h1>Create a category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>Your Categories</h1>
<ul>
<% Category.all.each do |cat| %>
	<li>
		Category <%= cat.id %>: <%= cat.description %>
	</li>
<% end %>
</ul>
<%= link_to 'New Category', new_product_category_path %></br>
<%= link_to 'Back', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Rainforest" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    

    <nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "Rainforest", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <li><%= link_to "New Product", new_product_path %></li>
      <li class="divider"></li>
      <li><%= link_to "New Category", new_category_path %></a>
      </li>
      <li class="divider"></li>
      <li><%= link_to "All Products", products_path %></a>
      </li>
      <li class="divider"></li>
      <li><%= link_to "All Categories", categories_path %></a>
      </li>
      <li class="divider"></li>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <li class="has-form">
        <form>
          <div class="row collapse">
            <div class="small-8 columns">
              <input type="text">
            </div>
            <div class="small-4 columns">
              <a href="#" class="alert button">Search</a>
            </div>
          </div>
        </form>
      </li>
    </ul>
  </section>
</nav>
<div class="large-5 large-centered columns">

    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
    
    <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.name %>. <%= link_to "Profile", user_path(current_user.id) %><%= link_to " Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
     </p>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

<%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label "name" %><br>
    <%= f.text_field "name" %>
  </p>
  <p>
    <%= f.label "description" %><br>
    <%= f.text_field "description" %>
  </p>
  <p>
    <%= f.label "price_in_cents" %><br>
    <%= f.text_field "price_in_cents" %>
  </p>
   <p>
  <p>
    <%= f.label "category" %><br>
    <%= f.collection_select :category_id, Category.all, :id, :description %>
  </p>
  </p>
  <p>
    <%= submit_tag "Save", id: "submit", class: "button" %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit a product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>All Products</h1>
<% @products.each do |product| %>
	  <div class="front">
	  	<h3><%= product[:name] %></h3>
	  	<%= product[:description] %></br>
	  	in: <%= product.category.description %></br>
	  	<%= product.formatted_price + " Dollars" %></br>
	  	<%= product.reviews.all.count.to_s + " Reviews" %></br>
	  	<%= link_to 'Show', product_path(product) %>
	  	
	  	<% if current_user %>
	  	<a href="<%=  edit_product_path(product) %>">edit product</a>
	  	<%= link_to 'Destroy', product_path(product),
	  	method: :delete, data: { confirm: 'Are you sure?' } %>
	  	<% end %>
	</div>
	<hr>
<% end %>

app/views/products/new.html.erb
<h1>Register a new Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p>
  <%= @product.description %>
  <%= @product.formatted_price + " Dollars" %></br>
  <%= @product.category.description %>
  <%= link_to 'Back', products_path %>
</p>


  <h3>Reviews</h3>
  
  <% @product.reviews.order("reviews.created_at desc").each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.name %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>

<% if current_user %>
  <h4>New Review</h4>

  <%= render 'reviews/form' %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit :class => "button" %>
    </div>
  <% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation"> 
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>. 
		</div>
		<ul> 
			<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li> 
			<% end %> 
		</ul>
	</div> 
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit :class => "button" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit your Profile</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Profile of <%= current_user.name %></h1>

<p>
	Username: <%= current_user.name %>
</p>
<p>
	Email: <%= current_user.email %>
</p>
<p>
	<%= link_to "Edit Profile", edit_user_path(@user) %>
</p>